@WebApi_HostAddress = http://localhost:5159
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQWhtZWQiLCJqdGkiOiIyYzJiMjIxMi01N2NiLTQwMjgtYmY2My1lMjE5YjIxNzVhODUiLCJleHAiOjE3NzcyMTc2NjUsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTE1OSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTE1OSJ9.U1wHDbY-pmwQBAepgp4vQwBcdov09vA0UsWciFeOweU

###
GET {{WebApi_HostAddress}}/Api/Student
Authorization: Bearer {{token}}
###
GET {{WebApi_HostAddress}}/Api/Student
Authorization: Bearer {{token}}

###
POST {{WebApi_HostAddress}}/Api/Student
Content-Type: application/json
{
    
    "name": "Mahmoud",
    "address": "ALex",
    "age": 22,
    "DOB":"2004-06-15",
    "imageUrl": "He.peg"
  
}
###
GET {{WebApi_HostAddress}}/Api/Student/1


###
PUT {{WebApi_HostAddress}}/Api/Student/1
Content-Type: application/json
{
    "name": "Mohamed",
    "address": "ALex",
    "age": 28,
    "imageUrl": "https://th.bing.com/th/id/OIP.xcKD3w58xiM1l9211ExZMwHaE8?w=252&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3"
}

###
DELETE {{WebApi_HostAddress}}/Api/Student/7

###
GET {{WebApi_HostAddress}}/Api/Student/Test-error

###
GET {{WebApi_HostAddress}}/error

###
GET {{WebApi_HostAddress}}/Api/Department

###
GET {{WebApi_HostAddress}}/Api/Department/1

###
POST {{WebApi_HostAddress}}/Api/Department
Content-Type: application/json

{
  "name": "IS",
  "Location": "ALex"
}

###
DELETE {{WebApi_HostAddress}}/Api/Department/4

###
POST {{WebApi_HostAddress}}/Api/Account/Register
Content-Type: application/json

{
  "name": "Ahmed",
  "email": "ahmed@example.com",
  "address": "Cairo, Egypt",
  "password": "1234",
  "confirmPassword": "1234"
}

### 
POST {{WebApi_HostAddress}}/api/account/login
Content-Type: application/json

{
  "name": "Ahmed",
  "password": "1234"
}