@WebApi_HostAddress = http://localhost:5159

GET {{WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{WebApi_HostAddress}}/Api/Student
###
POST {{WebApi_HostAddress}}/Api/Student
Content-Type: application/json
{
    
    "name": "Mahmoud",
    "address": "ALex",
    "age": 22,
    "DOB":"2004-06-15",
    "imageUrl": "He.png"
  
}
###
GET {{WebApi_HostAddress}}/Api/Student/1


###
PUT {{WebApi_HostAddress}}/Api/Student/1
Content-Type: application/json
{
    "name": "Mohamed",
    "address": "ALex",
    "age": 28,
    "imageUrl": "https://th.bing.com/th/id/OIP.xcKD3w58xiM1l9211ExZMwHaE8?w=252&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3"
}

###
DELETE {{WebApi_HostAddress}}/Api/Student/7

###
GET {{WebApi_HostAddress}}/Api/Student/Test-error

###
GET {{WebApi_HostAddress}}/error

###
GET {{WebApi_HostAddress}}/Api/Department


